EXCEPTION error. 
ok
  0: A.foo=                    tests/negative/setter3_test.toit:7:5
  1: main                      tests/negative/setter3_test.toit:12:9
